const TOKYO_CENTER_LAT = 35.68951;
const TOKYO_CENTER_LNG = 139.69171;
const MAIN_PIN_ICON_HEIGHT = 52;
const MAIN_PIN_ICON_WIDTH = 52;
const MAIN_PIN_ANCHOR_X = 26;
const MAIN_PIN_ANCHOR_Y = 52;
const PIN_ICON_HEIGHT = 40;
const PIN_ICON_WIDTH = 40;
const PIN_ANCHOR_X = 20;
const PIN_ANCHOR_Y = 40;
const ZOOM_DEFAULT = 12;
const SIMILAR_ANNOUNCEMENTS_COUNT = 10;
const TIME = 500;

export {
  TOKYO_CENTER_LNG,
  MAIN_PIN_ANCHOR_Y,
  MAIN_PIN_ICON_HEIGHT,
  MAIN_PIN_ICON_WIDTH,
  PIN_ANCHOR_X,
  PIN_ANCHOR_Y,
  PIN_ICON_HEIGHT,
  PIN_ICON_WIDTH,
  TOKYO_CENTER_LAT,
  MAIN_PIN_ANCHOR_X,
  ZOOM_DEFAULT,
  SIMILAR_ANNOUNCEMENTS_COUNT,
  TIME
};
